POST http://localhost:5235/breakfasts
Content-Type: application/json

{
    "name": "V",
    "description": "Vegan everything! Join us for a healthy breakfast..",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "savory": [
        "Oatmeal",
        "Avocado Toast",
        "Omelette",
        "Salad"
    ],
    "Sweet": [
        "Cookie"
    ]
}

###
GET http://localhost:5235/Breakfasts/8b948c9b-b8bb-4984-8461-bd0b2ccea31b